### ISSUE TITLE
longest returned code?

### ISSUE THREAD

**Issue by aromanocohen** [AHgPuK/id-shorter#1]
if I give a mongo id to the encode method, what is the longest (in number of digits) short code returned?

**Comment by AHgPuK** [comment]
It depends on charset you want to convert to. 
In a case a charset length is not a power of two it can be vary.

**Comment by aromanocohen** [comment]
Thank you very much for your awnser.

I'am using: 01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

37 characters. I need a fixed digits code so i'am padding the result with left zeros to achieve 12 digits but i'am not shure if you will return more than 12 digits (That would be a problem for me). Do you recomend me to use 32 characters instead so I can have a fixed digits code?

**Comment by AHgPuK** [comment]
Using your encoding charset (BTW 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ is correct, you have duplicated 0 before A) the max length of result is 18 chars in the worst case.
If you use 0123456789ABCDEFGHIJKLMNOPQRSTUV then length is constant - 11 chars.

**Comment by aromanocohen** [comment]
Thank you very much for your awnser, I will use 0123456789ABCDEFGHIJKLMNPQRSTUVX with one modificatión: I'am taking out the "O" and adding the "X" to prevent human confusion between "0" and "O" when reading and typing the code. I suppose that I will receive 11 chars constant length right?

**Comment by AHgPuK** [comment]
Yes.
